//! The string table (m0_contrat.md §4.1): every user-visible string of the desktop and web app, one row per
//! `key = "text"` of the contract's `strings` block, in its order. `{name}` is a placeholder filled at run time
//! (§4.12). G-STR (scope `strings`, crates/sr-app/tests/strings.rs) reads the contract and this table both ways: the
//! same keys, byte-identical texts. A text changes in the contract first, then here.

/// Every row of §4.1, `(key, text)`.
pub const STRINGS: &[(&str, &str)] = &[
    ("app.title", "Sandbox Reactions"),
    ("time.pause", "Pause"),
    ("time.play", "Play"),
    ("time.step", "Step"),
    ("time.rung", "×{rung}"),
    ("time.speed", "Speed ×{rung}"),
    ("time.speed_capped", "Speed ×{rung} (running ×{actual})"),
    ("time.paused", "Paused"),
    ("time.slowdown", "Slow down for big events"),
    ("banner.ignition", "Slowed down: hydrogen ignition — press + to speed up again"),
    ("banner.core_collapse", "Slowed down: core collapse — press + to speed up again"),
    ("banner.supernova", "Slowed down: supernova — press + to speed up again"),
    ("edge.label", "World edge:"),
    ("edge.leave", "Leave for good"),
    ("edge.bounce", "Bounce back"),
    ("world.clear", "Clear world"),
    ("world.clear_confirm", "Clear the world? Everything in it will be lost."),
    ("world.clear_yes", "Clear"),
    ("world.clear_no", "Cancel"),
    ("tools.heading", "Tools"),
    ("tools.brush", "Brush"),
    ("tools.eraser", "Eraser"),
    ("tools.heat", "Heat"),
    ("tools.cool", "Cool"),
    ("tools.brush_size", "Brush size"),
    ("tools.element_heading", "Element"),
    ("element.H", "Hydrogen"),
    ("element.He", "Helium"),
    ("element.C", "Carbon"),
    ("element.O", "Oxygen"),
    ("element.Ne", "Neon"),
    ("element.Mg", "Magnesium"),
    ("element.Si", "Silicon"),
    ("element.S", "Sulfur"),
    ("element.Fe", "Iron"),
    ("element.n", "Neutron matter"),
    ("presets.heading", "Drop a star"),
    ("presets.sun", "Sun-like star"),
    ("presets.sun_note", "1 Sun · ends as a white dwarf"),
    ("presets.massive", "Massive star"),
    ("presets.massive_note", "15 Suns · ends in a supernova"),
    ("presets.giant", "Giant star"),
    ("presets.giant_note", "40 Suns · ends as a black hole"),
    ("presets.place_hint", "Click in the world to drop the star. Esc cancels."),
    ("presets.no_room", "Not enough room here for this star."),
    ("views.heading", "View"),
    ("views.glow", "Glow"),
    ("views.heat", "Heat"),
    ("views.element", "Element"),
    ("views.density", "Density"),
    ("star.heading", "Star"),
    ("star.none", "No star yet. Paint gas or drop a star."),
    ("star.select_hint", "Right-click a star to select it."),
    ("star.mass", "Mass: {mass}"),
    ("star.fate", "Fate: {fate}"),
    ("star.ending", "Ending: {ending}"),
    ("star.age", "Age: {age}"),
    ("star.rate", "1 s ≈ {rate}"),
    ("star.surface", "Surface: {temperature}"),
    ("star.core", "Core: {temperature}"),
    ("fate.failed_star", "failed star (too light to ignite)"),
    ("fate.white_dwarf", "white dwarf"),
    ("fate.supernova", "supernova, then a neutron star"),
    ("fate.black_hole", "black hole"),
    ("fate.close_call", "{a} or {b} (close call)"),
    ("ending.failed_star", "failed star"),
    ("ending.white_dwarf", "white dwarf"),
    ("ending.neutron_star", "neutron star"),
    ("ending.black_hole", "black hole"),
    ("stage.cloud", "Gas cloud"),
    ("stage.collapsing", "Collapsing cloud"),
    ("stage.protostar", "Protostar: contracting"),
    ("stage.failed_star", "Failed star: too light to ignite"),
    ("stage.main_sequence", "Main sequence: burning hydrogen"),
    ("stage.h_shell", "Red giant: burning a hydrogen shell"),
    ("stage.h_shell_super", "Supergiant: burning a hydrogen shell"),
    ("stage.he_core", "Red giant: burning helium"),
    ("stage.he_core_super", "Supergiant: burning helium"),
    ("stage.he_shell", "Giant: burning a helium shell"),
    ("stage.c_burn", "Supergiant: burning carbon"),
    ("stage.ne_burn", "Supergiant: burning neon"),
    ("stage.o_burn", "Supergiant: burning oxygen"),
    ("stage.si_burn", "Supergiant: burning silicon"),
    ("stage.iron_core", "Supergiant: iron core"),
    ("stage.core_collapse", "Core collapse"),
    ("stage.supernova", "Supernova"),
    ("stage.planetary_nebula", "Planetary nebula: shedding its shell"),
    ("stage.white_dwarf", "White dwarf: cooling"),
    ("stage.neutron_star", "Neutron star"),
    ("stage.black_hole", "Black hole"),
    ("inspect.heading", "Cell"),
    ("inspect.empty", "Hover over a cell to inspect it."),
    ("inspect.vacuum", "Empty space"),
    ("inspect.mix_item", "{element} {percent}%"),
    ("inspect.mix_sep", " · "),
    ("inspect.temperature", "Temperature: {temperature}"),
    ("inspect.density", "Density: {density} (sandbox units)"),
    ("inspect.speed", "Speed: {speed} cells per time unit (Mach {mach})"),
    ("units.suns", "{value} Suns"),
    ("units.kelvin", "{value} K"),
    ("units.kelvin_million", "{value} million K"),
    ("units.kelvin_billion", "{value} billion K"),
    ("units.milliseconds", "{value} milliseconds"),
    ("units.seconds", "{value} seconds"),
    ("units.days", "{value} days"),
    ("units.years", "{value} years"),
    ("units.years_thousand", "{value} thousand years"),
    ("units.years_million", "{value} million years"),
    ("units.years_billion", "{value} billion years"),
    ("units.years_trillion", "{value} trillion years"),
    ("status.line", "{adapter} · {fps} fps · {steps} steps per frame · {width} × {height} cells"),
    ("error.no_adapter", "No compatible graphics card found. Sandbox Reactions needs a graphics card with Vulkan, Metal or DirectX 12 support."),
    ("error.device_lost", "The graphics card stopped responding. Please restart Sandbox Reactions."),
    ("web.loading", "Loading Sandbox Reactions…"),
    ("web.no_webgpu_title", "Sandbox Reactions needs WebGPU"),
    ("web.no_webgpu_body", "Your browser does not support WebGPU yet. Sandbox Reactions uses it to run its physics on your graphics card."),
    ("web.no_webgpu_browsers", "It runs in Google Chrome on Windows, macOS and ChromeOS (and on Linux with recent Intel or NVIDIA graphics), in Safari 26, and in Firefox on Windows and macOS."),
];

/// The text of `key`. A key the table does not hold is a bug in the caller, not a runtime condition.
#[cfg_attr(target_arch = "wasm32", allow(dead_code))]
pub fn get(key: &str) -> &'static str {
    STRINGS.iter().find(|(k, _)| *k == key).map(|(_, text)| *text).unwrap_or_else(|| panic!("no string `{key}` (§4.1)"))
}
